services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: piggytrack_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: finance
      MARIADB_USER: finance_user
      MARIADB_PASSWORD: finance_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: piggytrack_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: finance_user
      DB_PASSWORD: finance_pass
      DB_NAME: finance
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    container_name: piggytrack_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  db_data:
